### ISSUE TITLE
Pure FEM part Error

### ISSUE THREAD

**Issue by PeriHub** [PeriHub/PeriLab.jl#132]
@CWillberg I have a question about the horizon, when I try to calculate pure FEM part. 
Should the horizon be as 1*dxFEM, or sqrt(2)*dxFEM (the diagonal of the element). 
I got the error:
The determinat of the Jacobian is -0.0014433756729740645 in local element 1, and must be greater zero.

**Comment by CWillberg** [comment]
FEM is now verified and works fine.
