### ISSUE TITLE
[Feature]: Variable material and damage properties along a given direction

### ISSUE THREAD

**Issue by oldninja** [PeriHub/PeriLab.jl#143]
### What are you trying to do and how would you want to do it differently?

The current material and damage models assume fixed values for parameters such as the elastic modulus, density, and/or critical stretch. However, we would like to implement a variable model in which these properties are assigned based on a given variable (in this case location-dependent). 

As I understand the code right now, you can try to use the approach as shown in this example: [examples/RVE/RVE_abaqus.yaml](https://github.com/PeriHub/PeriLab.jl/blob/main/examples/RVE/RVE_abaqus.yaml), which requires some pre-processing before setting up the input file on your end.

**Comment by JTHesse** [comment]
I've just added the possibility to define `Bulk_Modulus`, `Shear_Modulus`, `Young's_Modulus`, `Poisson's_Ratio` or `Critical_Value` in the mesh input file. Those will override related values in the yaml input:

```
header: x y block_id volume Bulk_Modulus
-1.5 0 1 1.e-01 2.5e+3
-0.5 0 1 1.e-01 3.5e+3
...
```

Functions in values f.e.: `Critical_Value: 10*t` for time-dependent values will be discussed asap.

**Comment by oldninja** [comment]
Awesome! Thank you so much @JTHesse for this fast turn around!!

**Comment by JTHesse** [comment]
Yes exactly, the calculated elastic material parameters will also be available as output variables, to make sure everything is as expected -> [Test yaml](https://github.com/PeriHub/PeriLab.jl/blob/main/test/fullscale_tests/test_material_field/material_field.yaml)

**Comment by JTHesse** [comment]
As the location-dependent variables are supported, I'm going to close this. The other feature will be continued here #159

**Comment by CWillberg** [comment]
There are several problems in the implementation that has been solved now.
