### ISSUE TITLE
[Feature]: CUDA Support

### ISSUE THREAD

**Issue by JTHesse** [PeriHub/PeriLab.jl#149]
### What are you trying to do and how would you want to do it differently?

PeriLab should allow utilizing GPUs https://cuda.juliagpu.org/stable/

### Implementation details

[CUDA.jl](https://cuda.juliagpu.org/stable/) should allow the needed features. In the future [CUDA aware MPI ](https://juliaparallel.org/MPI.jl/stable/knownissues/#CUDA-aware-MPI) also worth looking into.

### Would you be willing to submit a PR?

Yes

**Comment by CWillberg** [comment]
We discussed it already. For special applications it is possible. But the whole code has to be restructured and/or becomes unreadable. 

Therefore, I close the issue, because from the easy to use point of view it makes no sense.
