### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by Lumos1110** [PeriHub/PeriLab.jl#2]
Hello, I am getting an error after running the instruction you gave me。The instruction is as follows: 
`using Pkg
Pkg.test("PeriLab") # Warning! This will take more than 30 minutes.`

Here is the error instruction:

Test Summary:                                       | Pass  Error  Total      Time
PeriLab                                             | 2298     24   2322  11m04.4s
  unit_tests                                        | 2282      8   2290   1m47.1s
    ut_perilab                                      |    3             3      0.2s
    FEM                                             |  326      2    328     17.0s
      ut_FEM_routines                               |  159      1    160     10.5s
        ut_jacobi                                   |   31      1     32      2.7s
        ut_lumped_mass                              |   17            17      2.0s
        ut_get_FE_material_model                    |    2             2      0.1s
        ut_get_polynomial_degree                    |   16            16      1.0s
        ut_get_number_of_integration_points         |    5             5      0.0s
        ut_get_weights_and_integration_points       |    4             4      0.1s
        ut_get_multi_dimensional_integration_points |   53            53      0.0s
        ut_create_element_matrices                  |   31            31      0.1s
      ut_FEM_Factory                                |  134      1    135      5.7s
        ut_valid_models                             |    6             6      0.0s
        ut_init_FEM                                 |   19      1     20      2.8s
        ut_eval                                     |   96            96      1.9s
        ut_get_FEM_nodes                            |   13            13      0.0s
      ut_lagrange_element                           |   33            33      0.8s
    Compute                                         |  120           120      1.8s
    Support                                         |  696      3    699     18.9s
      Parameters                                    |  206      3    209     10.3s
        ut_parameter_handling                       |  206      3    209     10.3s
          ut_get_element_degree                     |    6             6      0.1s
          ut_get_element_type                       |    3             3      0.0s
          ut_get_output_type                        |    6             6      0.1s
          ut_get_bond_filters                       |    8             8      0.3s
          ut_node_sets                              |   21      1     22      0.7s
          ut_node_set                               |    4      1      5      0.1s
          ut_validate_yaml                          |    9             9      0.3s
          ut_get_external_topology_name             |    3             3      0.1s
          ut_get_mesh_name                          |    2             2      0.0s
          ut_get_output_filenames                   |    3      1      4      0.3s
          get_output_frequency                      |   10            10      0.1s
          ut_get_outputs                            |   19            19      0.6s
          ut_get_computes                           |    6             6      0.2s
          ut_get_computes_names                     |    2             2      0.2s
          ut_get_bc_definitions                     |    5             5      0.0s
          ut_get_solver_options                     |   12            12      0.1s
          ut_get_number_of_blocks                   |    5             5      0.1s
          ut_block_values                           |   31            31      0.4s
          ut_solver                                 |   16            16      0.3s
          ut_find_data_files                        |    3             3      0.2s
          ut_get_model_parameter                    |   15            15      0.6s
          get_physics_option                        |   15            15      0.7s
          ut_check_for_duplicates                   |    2             2      0.0s
      ut_data_manager                               |  297           297      3.5s
      ut_helpers                                    |   45            45      1.1s
      ut_geometry                                   |  148           148      4.0s
    Core                                            |   94      1     95     21.8s
      Solver                                        |   14            14     20.1s
      Module_inclusion                              |    1      1      2      0.2s
        ut_find_jl_files                            |    1      1      2      0.1s
      ut_BC_manager                                 |   79            79      1.6s
    IO                                              |  559      2    561     17.0s
      ut_exodus_export                              |  133      1    134      2.7s
        ut_get_block_nodes                          |    4             4      0.1s
        ut_paraview_specifics                       |    3             3      0.1s
        ut_get_paraview_coordinates                 |   64            64      0.0s
        ut_create_result_file                       |   13            13      0.1s
        ut_init_results_in_exodus                   |   13            13      0.1s
        ut_write_results_in_exodus                  |   36            36      0.2s
      ut_read_inputdeck                             |   12            12      2.2s
      ut_IO                                         |  136      1    137      6.3s
        ut_get_results_mapping                      |   58            58      2.1s
        ut_init_write_result_and_write_results      |   75      1     76      1.4s
        ut_show_block_summary                       |               None      1.4s
        ut_init_orientations                        |    3             3      0.2s
      ut_mesh_data                                  |  207           207      4.5s
      ut_bond_filter                                |   59            59      0.9s
      ut_logging                                    |   12            12      0.4s
    MPI                                             |  137           137     12.9s
    Physics                                         |  347           347     17.4s
  fullscale_tests                                   |   16     16     32   9m17.4s
    test_additive_simple                            |    1      1      2     28.9s
    test_test_bond_based_elastic                    |    1      1      2     30.4s
    test_heat_transfer                              |    1      1      2     29.7s
    test_BCs                                        |    1      1      2     28.6s
    test_PD_Solid_Elastic                           |    1      1      2     30.8s
    test_PD_Solid_Elastic_3D                        |    1      1      2     30.7s
    test_Critical_stretch                           |    1      1      2     31.0s
    test_critical_energy                            |    1      1      2     31.9s
    test_thermal_expansion                          |    1      1      2     42.0s
    test_thermal_flow                               |    1      1      2     28.9s
    test_Correspondence_Elastic                     |    1      1      2     36.9s
    test_Correspondence_Elastic_Plastic             |    1      1      2     37.8s
    test_Correspondence_Elastic_with_zero_E_control |    1      1      2     40.5s
    test_Correspondence_Elastic                     |    1      1      2     40.6s
    test_DCB                                        |    1      1      2     47.5s
    test_FEM                                        |    1      1      2     41.2s
ERROR: LoadError: Some tests did not pass: 2298 passed, 0 failed, 24 errored, 0 broken.
in expression starting at C:\Users\Lsb18\.julia\packages\PeriLab\pZpHW\test\runtests.jl:19
ERROR: Package PeriLab errored during testing

**Comment by CWillberg** [comment]
We look into it. The test running at our system. Please try an update. Currently all but one test works. I fixed it and it will work in a few hours.

This is a mirror from our gitlab account. If you are interessted in working with us. Contact us there.
https://gitlab.com/dlr-perihub/PeriLab.jl
