### ISSUE TITLE
a question about example

### ISSUE THREAD

**Issue by Lumos1110** [PeriHub/PeriLab.jl#3]
Hello, I got a file "DCBmodel_Output1_red.e" by running the example file "examples/DCB/DCBmodel.yaml" in the documentation, what software can I use to run it and visualize it?
Also is it possible for the program to pre-join cracks? I didn't find any instructions about cracks :(
If you have time to describe the documentation in more detail that would be great!

**Comment by JTHesse** [comment]
Hi there, in order to visualize your results we can recommend [ParaView](https://www.paraview.org/), it's free and very extensive.

Yes you can use a Bond-Filter to do that. For example a rectangular plane:

```
PeriLab:
  Discretization:
    Input Mesh File: mesh.txt
    Node Sets:
      Node Set 1: ns1.txt
    Type: Text File
    Bond Filters:
      bf_1:
        Bottom Length: 2.0
        Bottom Unit Vector X: 1.0
        Bottom Unit Vector Y: 0.0
        Bottom Unit Vector Z: 0.0
        Lower Left Corner X: -0.5
        Lower Left Corner Y: 0.0
        Lower Left Corner Z: -1.0
        Normal X: 0.0
        Normal Y: 1.0
        Normal Z: 0.0
        Side Length: 2.0
        Type: Rectangular_Plane
  ...
```
