### ISSUE TITLE
A question about the use of the software

### ISSUE THREAD

**Issue by Lumos1110** [PeriHub/PeriLab.jl#5]
Hi, thanks for your patience, I watched and subscribed to your channel on youtube and I was wondering how to proceed to get an interface like the one in your video, that looks more like a piece of software, and I'm currently running it by using the julia package in vscode.
I'm new to gitlab, how can I join your project and collaborate?
Also since I've been using matlab before, julia is a very new language for me, I'll keep learning and if I have new questions I'll submit them to you.
Peridynamic is my PhD project and I think your software will help me a lot with my project, I will keep using it and keep following it, thanks for your contribution to the community!

**Comment by JTHesse** [comment]
Hi @Lumos1110, yes that is the [PeriHub](https://gitlab.com/dlr-perihub/PeriHub) Web Framework.
The Framework is designed for Peridynamic User only; you can run it locally with Docker. Soon there will be a hosted URL . 
However, as you are aiming to develop in julia, I suggest you create a fork of the [gitlab repository](https://gitlab.com/dlr-perihub/PeriLab.jl). We can further discuss this via [e-mail](mailto:jan-timo.hesse@dlr.de).
